name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and run tests
        run: mvn clean test

      - name: Upload ExtentReport
        uses: actions/upload-artifact@v4

        with:
          name: extent-report
          path: target/test-output/extentReport.html

      - name: Upload Log File
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: target/test-output/logs/test.log
